### ISSUE TITLE
[Request] a release

### ISSUE THREAD

**Issue by biopsin** [stevommmm/gbg#1]
Heya and kudos for this. 
To things; mind making a release out of this, as my distro don't allow packing from master. 
And second I noticed a issue using gbg with any compositor (xcompmgr/compton/picom), now I understand it targets tilling but removing the XFreePixmap 91line won't freak the compositor out. Have not done extensive test if this creates memleaks, but a comment in the code would have being nice;)
Thank you and have a nice day!

**Comment by stevommmm** [comment]
`1.0.1` tagged and pushed for you. There is now a `make BUILD=compositing` that will do what you're after. 
I'm not really sure of the ramifications of leaving off the free within the running X. I'll have to do some testing at some stage

Going by the man for `XSetWindowBackgroundPixmap` it seems to imply it should be freed at *some* stage.
>  The XSetWindowBackgroundPixmap function sets the background pixmap  of
>  the window to the specified pixmap.  The background pixmap can immedi‐
>  ately be freed if no further explicit references to it are to be made.
